version: '3.5'

services:
  db_devops:
    container_name: db_devops
    build: ./stock_db
    env_file:
      - .env.db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app_devops:
    build: 
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env.app
    volumes:
      - static:/home/app/static
    depends_on:
      - db_devops

  nginx_devops:
    build: ./stock_nginx
    volumes:
      - static:/home/app/static
    ports:
      - 8008:80
    depends_on:
      - app_devops

volumes:
  pgdata:
  static: