# Generated by Django 4.2.7 on 2023-11-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('red', 'red color'), ('green', 'green color'), ('blue', 'blue color'), ('yellow', 'yellow color'), ('magenta', 'magenta')], max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boxes.boxmodel')),
            ],
        ),
        migrations.AddField(
            model_name='boxmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boxes.usermodel'),
        ),
    ]
